-- Execute no Supabase SQL Editor.
-- A tabela precisa existir antes destas políticas.
create table if not exists public.noticias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumo text,
  conteudo text not null,
  imagem text,
  categoria text,
  created_at timestamp with time zone default now()
);

alter table public.noticias enable row level security;

drop policy if exists "Todos podem ler noticias" on public.noticias;
drop policy if exists "Usuarios autenticados podem publicar" on public.noticias;
drop policy if exists "Usuarios autenticados podem editar" on public.noticias;
drop policy if exists "Usuarios autenticados podem excluir" on public.noticias;

create policy "Todos podem ler noticias"
on public.noticias for select to anon, authenticated using (true);

create policy "Usuarios autenticados podem publicar"
on public.noticias for insert to authenticated with check (true);

create policy "Usuarios autenticados podem editar"
on public.noticias for update to authenticated using (true) with check (true);

create policy "Usuarios autenticados podem excluir"
on public.noticias for delete to authenticated using (true);
