-- CURIONEWS: tabela e políticas de anúncios
create table if not exists public.anuncios (
    id bigint generated by default as identity primary key,
    nome text not null,
    imagem text not null,
    link text not null,
    posicao text not null default 'entre',
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.anuncios enable row level security;

drop policy if exists "Todos podem ver anuncios ativos" on public.anuncios;
drop policy if exists "Administrador pode ver todos anuncios" on public.anuncios;
drop policy if exists "Somente administrador pode inserir anuncios" on public.anuncios;
drop policy if exists "Somente administrador pode editar anuncios" on public.anuncios;
drop policy if exists "Somente administrador pode excluir anuncios" on public.anuncios;

create policy "Todos podem ver anuncios ativos"
on public.anuncios for select to anon, authenticated
using (ativo = true);

create policy "Administrador pode ver todos anuncios"
on public.anuncios for select to authenticated
using (auth.uid() = 'b71328fe-b51d-47f6-b3bd-dac00f7878f1'::uuid);

create policy "Somente administrador pode inserir anuncios"
on public.anuncios for insert to authenticated
with check (auth.uid() = 'b71328fe-b51d-47f6-b3bd-dac00f7878f1'::uuid);

create policy "Somente administrador pode editar anuncios"
on public.anuncios for update to authenticated
using (auth.uid() = 'b71328fe-b51d-47f6-b3bd-dac00f7878f1'::uuid)
with check (auth.uid() = 'b71328fe-b51d-47f6-b3bd-dac00f7878f1'::uuid);

create policy "Somente administrador pode excluir anuncios"
on public.anuncios for delete to authenticated
using (auth.uid() = 'b71328fe-b51d-47f6-b3bd-dac00f7878f1'::uuid);

grant select on public.anuncios to anon, authenticated;
grant insert, update, delete on public.anuncios to authenticated;
